general:
  area_height: 460
  area_width: 385
  z_up: 8
  z_down: 0
  feed_rate_draw: 4000 # Feed rate for drawing movements (mm/min)
  feed_rate_travel: 6000 # Feed rate for travel movements (mm/min)
  feed_rate_z: 1500 # Feed rate for Z-axis movements (mm/min)
papers:
  - height: 304.79999999999995
    name: 9x12
    width: 228.6
  - height: 355.6
    name: 11x14
    width: 279.4
  - height: 431.79999999999995
    name: 11x17
    width: 279.4
  - height: 406.4
    name: 12x16
    width: 304.8
  - height: 431.8
    name: 14x17
    width: 355.6
  - height: 457.2
    name: 12x18
    width: 304.8
  - name: 8.5x11
    width: 215.9
    height: 279.4
